# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c72aa4c4fa05da2f3d2f80e18ad5e8785041f052ffdf4da810cfa69e121028092482cd220f93925d2373a96f2023453cbe2355e57436754c8b787ce4c7fa2f36

test:
  secret_key_base: 9f696e9c4bfe94e11158c5559a87560285dcd1bde9255aeeb94e9e39789985bd6ca63814d66b6430dc37fc16cefae575cde0edb7c61b889ff90d9d06771c5aed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
